package com.thyo.animestream.plugins

import android.content.Context
import com.fasterxml.jackson.annotation.JsonProperty
import com.thyo.animestream.AcraApplication.Companion.context
import com.thyo.animestream.AcraApplication.Companion.getKey
import com.thyo.animestream.AcraApplication.Companion.setKey
import com.thyo.animestream.R
import com.thyo.animestream.amap
import com.thyo.animestream.app
import com.thyo.animestream.mvvm.logError
import com.thyo.animestream.mvvm.safe
import com.thyo.animestream.mvvm.safeAsync
import com.thyo.animestream.plugins.PluginManager.getPluginSanitizedFileName
import com.thyo.animestream.plugins.PluginManager.unloadPlugin
import com.thyo.animestream.ui.settings.extensions.REPOSITORIES_KEY
import com.thyo.animestream.ui.settings.extensions.RepositoryData
import com.thyo.animestream.utils.AppUtils.tryParseJson
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import java.io.BufferedInputStream
import java.io.File
import java.io.InputStream
import java.io.OutputStream

/**
 * Comes with the app, always available in the app, non removable.
 * */

data class Repository(
    @JsonProperty("iconUrl") val iconUrl: String?,
    @JsonProperty("name") val name: String,
    @JsonProperty("description") val description: String?,
    @JsonProperty("manifestVersion") val manifestVersion: Int,
    @JsonProperty("pluginLists") val pluginLists: List<String>
)

/**
 * Status int as the following:
 * 0: Down
 * 1: Ok
 * 2: Slow
 * 3: Beta only
 * */
data class SitePlugin(
    // Url to the .cs3 file
    @JsonProperty("url") val url: String,
    // Status to remotely disable the provider
    @JsonProperty("status") val status: Int,
    // Integer over 0, any change of this will trigger an auto update
    @JsonProperty("version") val version: Int,
    // Unused currently, used to make the api backwards compatible?
    // Set to 1
    @JsonProperty("apiVersion") val apiVersion: Int,
    // Name to be shown in app
    @JsonProperty("name") val name: String,
    // Name to be referenced internally. Separate to make name and url changes possible
    @JsonProperty("internalName") val internalName: String,
    @JsonProperty("authors") val authors: List<String>,
    @JsonProperty("description") val description: String?,
    // Might be used to go directly to the plugin repo in the future
    @JsonProperty("repositoryUrl") val repositoryUrl: String?,
    // These types are yet to be mapped and used, ignore for now
    @JsonProperty("tvTypes") val tvTypes: List<String>?,
    @JsonProperty("language") val language: String?,
    @JsonProperty("iconUrl") val iconUrl: String?,
    // Automatically generated by the gradle plugin
    @JsonProperty("fileSize") val fileSize: Long?,
)

object RepositoryManager {
    const val ONLINE_PLUGINS_FOLDER = "Extensions"
    
    // URL Web Railway kamu yang memegang kendali penuh
    const val MY_WEB_REPO_URL = "https://extension-thyoapp.up.railway.app/repo.json" 

    val PREBUILT_REPOSITORIES: Array<RepositoryData> by lazy {
        getKey("PREBUILT_REPOSITORIES") ?: emptyArray()
    }
    private val GH_REGEX = Regex("^https://raw.githubusercontent.com/([A-Za-z0-9-]+)/([A-Za-z0-9_.-]+)/(.*)$")

    /* Convert raw.githubusercontent.com urls to cdn.jsdelivr.net if enabled in settings */
    fun convertRawGitUrl(url: String): String {
        if (getKey<Boolean>(context!!.getString(R.string.jsdelivr_proxy_key)) != true) return url
        val match = GH_REGEX.find(url) ?: return url
        val (user, repo, rest) = match.destructured
        return "https://cdn.jsdelivr.net/gh/$user/$repo@$rest"
    }

    suspend fun parseRepoUrl(url: String): String? {
        val fixedUrl = url.trim()
        return if (fixedUrl.contains("^https?://".toRegex())) {
            fixedUrl
        // MENGHAPUS NAMA LAMA DAN MENGGANTI MENJADI animestreamrepo
        } else if (fixedUrl.contains("^(animestreamrepo://)|(https://as\\.repo/\\??)".toRegex())) {
            fixedUrl.replace("^(animestreamrepo://)|(https://as\\.repo/\\??)".toRegex(), "").let {
                return@let if (!it.contains("^https?://".toRegex()))
                    "https://${it}"
                else fixedUrl
            }
        } else if (fixedUrl.matches("^[a-zA-Z0-9!_-]+$".toRegex())) {
            safeAsync {
                app.get("https://cutt.ly/${fixedUrl}", allowRedirects = false).let { it2 ->
                    it2.headers["Location"]?.let { url ->
                        if (url.startsWith("https://cutt.ly/404")) return@safeAsync null
                        if (url.removeSuffix("/") == "https://cutt.ly") return@safeAsync null
                        return@safeAsync url
                    }
                }
            }
        } else null
    }

    suspend fun parseRepository(url: String): Repository? {
        return safeAsync {
            // Take manifestVersion and such into account later
            app.get(convertRawGitUrl(url)).parsedSafe()
        }
    }

    private suspend fun parsePlugins(pluginUrls: String): List<SitePlugin> {
        // Take manifestVersion and such into account later
        return try {
            val response = app.get(convertRawGitUrl(pluginUrls))
            // Normal parsed function not working?
            // return response.parsedSafe()
            tryParseJson<Array<SitePlugin>>(response.text)?.toList() ?: emptyList()
        } catch (t: Throwable) {
            logError(t)
            emptyList()
        }
    }

    /**
     * Gets all plugins from repositories and pairs them with the repository url
     * */
    suspend fun getRepoPlugins(repositoryUrl: String): List<Pair<String, SitePlugin>>? {
        val repo = parseRepository(repositoryUrl) ?: return null
        return repo.pluginLists.amap { url ->
            parsePlugins(url).map {
                repositoryUrl to it
            }
        }.flatten()
    }

    suspend fun downloadPluginToFile(
        pluginUrl: String,
        file: File
    ): File? {
        return safeAsync {
            file.mkdirs()

            // Overwrite if exists
            if (file.exists()) {
                file.delete()
            }
            file.createNewFile()

            val body = app.get(convertRawGitUrl(pluginUrl)).okhttpResponse.body
            write(body.byteStream(), file.outputStream())
            file
        }
    }

    fun getRepositories(): Array<RepositoryData> {
        val myWebRepo = RepositoryData(
            name = "Repo Anime Thyo", 
            url = MY_WEB_REPO_URL 
        )
        
        // HANYA mengembalikan array berisi repo web milikmu.
        return arrayOf(myWebRepo)
    }

    private val repoLock = Mutex()
    
    suspend fun addRepository(repository: RepositoryData) {
        // Dilumpuhkan agar user tidak bisa menambah repo lain.
        return 
    }

    /**
     * Also deletes downloaded repository plugins
     * */
    suspend fun removeRepository(context: Context, repository: RepositoryData) {
        // Mencegah repo web milikmu dihapus
        if (repository.url == MY_WEB_REPO_URL) {
            return 
        }

        val extensionsDir = File(context.filesDir, ONLINE_PLUGINS_FOLDER)

        repoLock.withLock {
            val currentRepos = getKey<Array<RepositoryData>>(REPOSITORIES_KEY) ?: emptyArray()
            // No duplicates
            val newRepos = currentRepos.filter { it.url != repository.url }
            setKey(REPOSITORIES_KEY, newRepos)
        }

        val file = File(
            extensionsDir,
            getPluginSanitizedFileName(repository.url)
        )

        // Unload all plugins, not using deletePlugin since we
        // delete all data and files in deleteRepositoryData
        safe {
            file.listFiles { plugin: File ->
                unloadPlugin(plugin.absolutePath)
                false
            }
        }

        PluginManager.deleteRepositoryData(file.absolutePath)
    }

    private fun write(stream: InputStream, output: OutputStream) {
        val input = BufferedInputStream(stream)
        val dataBuffer = ByteArray(512)
        var readBytes: Int
        while (input.read(dataBuffer).also { readBytes = it } != -1) {
            output.write(dataBuffer, 0, readBytes)
        }
    }

    // --- [MESIN AUTO-INSTALL DARI WEB THYO] ---
    @Suppress("DEPRECATION_ERROR")
    suspend fun autoInstallMyRepo() {
        safeAsync {
            val myRepoUrl = MY_WEB_REPO_URL
            val plugins = getRepoPlugins(myRepoUrl) ?: return@safeAsync
            var isNewPluginDownloaded = false
            
            plugins.forEach { (_, plugin) ->
                val extensionsDir = File(context?.filesDir, ONLINE_PLUGINS_FOLDER)
                val repoDir = File(extensionsDir, getPluginSanitizedFileName(myRepoUrl))
                val pluginFile = File(repoDir, "${plugin.internalName}.cs3")
                
                // Cek apakah file sudah ada, biar gak di-download berulang kali
                if (!pluginFile.exists()) {
                    downloadPluginToFile(plugin.url, pluginFile)?.let {
                        isNewPluginDownloaded = true // Tandai kalau ada file baru yang masuk
                    }
                }
            }

            // Jika ada ekstensi baru yang selesai didownload, suruh aplikasi muat ulang semuanya!
            if (isNewPluginDownloaded) {
                context?.let { ctx ->
                    PluginManager.___DO_NOT_CALL_FROM_A_PLUGIN_loadAllOnlinePlugins(ctx)
                }
            }
        }
    }
    // ------------------------------------------
}
